export const CONFIG = {
  RPC_URL: process.env.ARC_RPC_URL || 'https://rpc.testnet.arc.network',
  DATABASE_URL: process.env.DATABASE_URL || 'postgresql://archiveagents:archiveagents@localhost:5432/archiveagents',
  EVALUATOR_PRIVATE_KEY: process.env.EVALUATOR_PRIVATE_KEY || '',
  PROVIDER_PRIVATE_KEY: process.env.PROVIDER_PRIVATE_KEY || '',
  LLM_API_KEY: process.env.LLM_API_KEY || '',
  LLM_MODEL: process.env.LLM_MODEL || 'mimo-v2.5-pro',
  LLM_BASE_URL: process.env.LLM_BASE_URL || 'https://token-plan-sgp.xiaomimimo.com/v1',
  APPROVAL_THRESHOLD: parseInt(process.env.APPROVAL_THRESHOLD || '70'),
  MAX_REVISIONS: parseInt(process.env.MAX_REVISIONS || '2'),
  POLL_INTERVAL_MS: parseInt(process.env.POLL_INTERVAL_MS || '15000'),
  MAX_DELIVERABLE_LENGTH: parseInt(process.env.MAX_DELIVERABLE_LENGTH || '10000'),
  AGENTIC_COMMERCE: '0x0747EEf0706327138c69792bF28Cd525089e4583' as `0x${string}`,
  EVALUATOR_ADDRESS: '0xC1FEf538dc6357435372CEb69970D4078F4d3528',
  CHAIN_ID: 5042002,
}
