-- 013_add_missing_indexes.sql — INTENTIONALLY NO-OP
--
-- Original content of this file was broken in three ways and never
-- successfully ran on any deployment:
--
--   1. CREATE INDEX CONCURRENTLY cannot run inside a BEGIN/COMMIT block,
--      and the migration runner (packages/indexer/src/db/migrate.ts)
--      always wraps each file in a transaction. Postgres aborted at the
--      first statement on every `pnpm migrate`, the file rolled back,
--      and `_migrations` never got an entry — so the runner re-tried
--      the same broken file forever.
--
--   2. The CREATE INDEX statements referenced columns that don't exist:
--        - job_applications.agent_address    (real column: applicant_address)
--        - job_applications.open_job_id      (real column: job_id)
--        - evaluations.status                (no such column; has `decision`)
--
--   3. Three of the indexes were already created in 010_create_marketplace.sql
--      and would have been redundant.
--
-- This file is preserved as a no-op so the migration runner can mark it
-- applied and stop retrying. The corrected indexes live in
-- 017_add_missing_indexes.sql.
--
-- See docs/DATABASE_SCHEMA.md for the rationale.

SELECT 1;
